### PR TITLE
Add screen background

### PR DESCRIPTION
**Pull request by trinhpham**
### Purpose of changes

Set the background desktop to solve #172 

### Types of changes
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### How has this been tested?

The logo appear :)

### CODE REVIEW

**Comment by trinhpham** [comment]
@budtmo I've made it, but I don't have time to test it right now.
Could you please help with [this build](https://travis-ci.org/trinhpham/docker-android/builds/556672186)?

Otherwise, I'll test it on tomorrow and report you the status :)

**Comment by budtmo** [comment]
Hi @trinhpham , 

Thanks a lot for the PR! sure, I will test it. sorry, that I just saw your PR, will merge and release it in the next version.

**Comment by budtmo** [comment]
btw, I just did a small refactoring. I think you need to rebase your branch with current state of my master branch to avoid conflict. @trinhpham

**Comment by trinhpham** [comment]
saw it.
Let me check

**Pull request merged**
